-- ==========================================
-- ISTE Orientation Registration - Master Supabase Reset Script
-- ==========================================
-- Copy and paste this script into your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new

-- 1. Drop existing table & sequence to clear corrupted state
DROP TABLE IF EXISTS public."Registrations" CASCADE;
DROP TABLE IF EXISTS public.registrations CASCADE;

-- 2. Create Registrations table fresh with auto-incrementing identity primary key
CREATE TABLE public."Registrations" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Admission Number" TEXT NOT NULL,
    "E-Mail ID" TEXT NOT NULL,
    "Phone Number" TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public."Registrations" ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow Public Insertion (Registration Form)
CREATE POLICY "Enable insert for all users"
ON public."Registrations"
FOR INSERT
TO public
WITH CHECK (true);

-- 5. Policy: Allow Public Reading (Admin Dashboard Data Fetching)
CREATE POLICY "Enable select for all users"
ON public."Registrations"
FOR SELECT
TO public
USING (true);

-- 6. Policy: Allow Public Deletion (Admin Record Management)
CREATE POLICY "Enable delete for all users"
ON public."Registrations"
FOR DELETE
TO public
USING (true);

-- 7. Performance Indexes
CREATE INDEX idx_registrations_created_at ON public."Registrations" (created_at DESC);
CREATE INDEX idx_registrations_admission ON public."Registrations" ("Admission Number");
