-- ==========================================
-- ISTE Orientation Registration - Supabase SQL Setup
-- ==========================================
-- Copy and paste this script into your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new

-- 1. Create the Registrations table
CREATE TABLE IF NOT EXISTS public."Registrations" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Admission Number" TEXT NOT NULL,
    "E-Mail ID" TEXT NOT NULL,
    "Phone Number" TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public."Registrations" ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow Anyone (Anon) to Register (INSERT)
DROP POLICY IF EXISTS "Allow anon public insert" ON public."Registrations";
CREATE POLICY "Allow anon public insert"
ON public."Registrations"
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 4. Policy: Allow Reading Registrations for Admin Dashboard (SELECT)
DROP POLICY IF EXISTS "Allow public read access" ON public."Registrations";
CREATE POLICY "Allow public read access"
ON public."Registrations"
FOR SELECT
TO anon, authenticated
USING (true);

-- 5. Policy: Allow Deleting Registrations (DELETE)
DROP POLICY IF EXISTS "Allow public delete access" ON public."Registrations";
CREATE POLICY "Allow public delete access"
ON public."Registrations"
FOR DELETE
TO anon, authenticated
USING (true);

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_registrations_created_at ON public."Registrations" (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_registrations_admission ON public."Registrations" ("Admission Number");

-- 7. Reset / Sync Primary Key ID Sequence
-- (Fixes "duplicate key value violates unique constraint Registrations_pkey")
SELECT setval(
    pg_get_serial_sequence('public."Registrations"', 'id'),
    COALESCE((SELECT MAX(id) FROM public."Registrations"), 0) + 1,
    false
);
